using KitchenSink.Database;
using Starcounter;

namespace KitchenSink.DataTableExamples.Simple
{
    public class BookViewModel : Json, IBound<Book>
    {
        // Those properties would be generated by TypedJSON
        public string Author { get; set; }
        public string Title { get; set; }
        public int Position { get; set; }
    }
}