using System;
using KitchenSink.Database;
using Starcounter;

namespace KitchenSink.DataTableExamples.Complex
{
    public class BookViewModel : Json, IBound<Book>
    {
        public string Display => $"{Data.Author}: {Data.Title}";

        public Action<BookViewModel> DeleteAction { get; set; }

        public void HandleDeleteTrigger()
        {
            DeleteAction?.Invoke(this);
        }

        // Those properties would be generated by TypedJSON
        public Book Data => (Book) base.Data;
        public string Author { get; set; }
        public string Title { get; set; }
        public int Position { get; set; }
    }
}